### ISSUE TITLE
Code deprecated

### ISSUE THREAD

**Issue by mortensen** [AlmasB/FXGL-WebApp#4]
This code still uses GameApp.customLaunch() which seems deprecated as by commit:

https://github.com/AlmasB/FXGL/commit/1815e4bd68dbdd43b323ae5d18a61e7166ad70a8#diff-d8d3d7867c84eb708473bdbac43302cfecd5f5f18400c19192f94bec7704eefa

The new way seems to be embeddedLaunch().

Also a maven example would be nice too.

**Comment by AlmasB** [comment]
Thanks, it has now been updated to the latest FXGL 17.3 with jpro 2023
